### ISSUE TITLE
Populating Custom Labels. How to?

### ISSUE THREAD

**Issue by dwestness** [tenable/integration-jira-cloud#197] opened 2022-10-02 11:07 UTC
I would like to populate the "Tenable Plugin Family" and "Tenable Plugin Name" fields as a label type in JIRA rather than short text.
Currently the issue i run into is that these fields often contain spaces and labels in JIRA do not support spaces.

I have worked around for some time now with a JIRA Automation rule that populates the custom label field for me and performs the character replacement to replace spaces with hypens for support as such:

```
{
    "fields": {
        "customfield_13750": ["{{issue.customfield_13748.replace(" ","-")}}"]
    }
}
```

I would like to get away from relying on these automation rules however as Jira cloud's executive limits per month are starting to become an issue.
Is there a way to perform the character replacement as part of the script natively instead to populate a label type?

**Comment by SteveMcGrath** [comment] 2022-11-03 16:56
Duplicate of #200

**Closed** 2022-11-03 16:57 UTC
Labels: duplicate, enhancement
