### ISSUE TITLE
Error uploading config file

### ISSUE THREAD

**Issue by FlyS3c** [tenable/integration-jira-cloud#243] opened 2024-02-01 18:42 UTC
I get to the step where I have to run tenable-jira on the config file, and get the below output. My config file is saved in the temp directory.

Command tenable-jira C:\temp\config.yaml

Output:
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\admin\AppData\Local\Programs\Python\Python312\Tenable\Scripts\tenable-jira.exe\__main__.py", line 4, in <module>
  File "C:\Users\admin\AppData\Local\Programs\Python\Python312\tenable\Lib\site-packages\tenable_jira\cli.py", line 31, in <module>
    from .transform import Tio2Jira
  File "C:\Users\admin\AppData\Local\Programs\Python\Python312\tenable\Lib\site-packages\tenable_jira\transform.py", line 3, in <module>
    from pkg_resources import resource_string as embedded
ModuleNotFoundError: No module named 'pkg_resources'

**Comment by SteveMcGrath** [comment] 2024-03-11 21:37
Duplicate of #242

**Closed by SteveMcGrath** 2024-03-11 21:37 UTC
