### ISSUE TITLE
TypeError: 'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by prikshitpathania** [tenable/integration-jira-cloud#236] opened 2023-11-23 07:32 UTC
Traceback (most recent call last):
  File "/jira/bin/tenable-jira", line 11, in <module>
    load_entry_point('tenable-jira-cloud==1.2.3', 'console_scripts', 'tenable-jira')()
  File "/jira/lib64/python3.6/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/jira/lib64/python3.6/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/jira/lib64/python3.6/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/jira/lib64/python3.6/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/jira/lib64/python3.6/site-packages/tenable_jira/cli.py", line 218, in cli
    ingest.ingest(since, first_discovery)
  File "/jira/lib64/python3.6/site-packages/tenable_jira/transform.py", line 736, in ingest
    self.create_issues(vulns)
  File "/jira/lib64/python3.6/site-packages/tenable_jira/transform.py", line 529, in create_issues
    self._process_open_vuln(v, fid)
  File "/jira/lib64/python3.6/site-packages/tenable_jira/transform.py", line 400, in _process_open_vuln
    issue, subissue, jql, sjql = self._process_vuln(vuln, fid)
  File "/jira/lib64/python3.6/site-packages/tenable_jira/transform.py", line 254, in _process_vuln
    'issuetype = "{}"'.format(self.subtask['name']),
TypeError: 'NoneType' object is not subscriptable

**Comment by SteveMcGrath** [comment] 2024-03-11 21:42
#233 is a dupe of this

**Closed by SteveMcGrath** 2024-03-11 21:42 UTC
Labels: bug, backlog
