### ISSUE TITLE
WAS vulns not importing

### ISSUE THREAD

**Issue by solution904** [tenable/integration-jira-cloud#151] opened 2021-10-19 13:48 UTC
Currently our Tenable.io > JIRA Cloud integration only imports vulns identified via hosts that have a Tenable agent installed.  Vulns identified as part of web app scans (WAS) in Teanble.io are not importing.  Is this an intended limitation of the integration, or is their a config. adjustment that can be done to have all identified vulns imported into JIRA?

**Comment by jay-hims** [comment] 2021-11-06 19:16
I have the same question. By taking a quick look at the code, it seems to me like a limitation of the integration. I'm wondering if there is an easy way to also retrieve WAS vulns?

**Comment by SteveMcGrath** [comment] 2021-11-29 16:57
Correct.  The Jira integration uses the cumulative state within Tenable.io in order to replicate the state of those issues over to Jira.  As there is currently no cumulative export API for WAS, there is sadly nothing that can be done here.  Manually tracking state yourself can be quite error-prone, and its best to wait for the IO platform to support WAS state.

**Comment by SteveMcGrath** [comment] 2021-11-29 16:58
duplicate of #310

**Closed** 2021-12-06 23:01 UTC
Labels: duplicate, question, api-issue
